# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Sync generated content

on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Sync generated content
      run: yarn sync

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: '**/*.md'
